# Generated by Django 5.0.4 on 2024-06-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appab', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
