# Generated by Django 5.0.4 on 2024-06-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appab', '0008_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
