# Generated by Django 5.0.4 on 2024-06-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appab', '0010_procedure_specialist_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='specialist',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='user',
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
        migrations.DeleteModel(
            name='Specialist',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
