# Generated by Django 5.0.4 on 2024-06-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appab', '0017_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
