# Generated by Django 5.0.4 on 2024-06-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appab', '0025_alter_profile_options_remove_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', upload_to='avatars/'),
        ),
    ]
